sudo: required
servcies:
  - docker

before_install:
  - docker build -t BhuwanSinghBisht/docker-react -f Dockerfile.dev .

scripts:
  - docker run -e CI=true BhuwanSinghBisht/docker-react npm run test